### ISSUE TITLE
[Task] Intern onboarding task (PM team)

### ISSUE THREAD

**Issue by yufansong** [TheAgentCompany/TheAgentCompany#201]
# Hint 
in rocketchat, host a NPC, then tell him the material about the nextcloud page, the plane page.

# Task 
you are an intern new to the group. you need to ask your leader xx in rocketchat about what content you need to familiarize yourself with, and study then and generate a summary doc locally as a markdown file. 

# checkpoint
* check the rocketchat history about whether we talked with the leader
* check the trajectory (by action or check whether the specific url happened twice) whether have access the nextcloud, plane, wiki, gitlab

**Comment by li-boxuan** [comment]
@bugsz Is this finished?
