### ISSUE TITLE
Finance Task: Salary Band Confirmation

### ISSUE THREAD

**Issue by neubig** [TheAgentCompany/TheAgentCompany#608]
This was generated by OpenHands and may need to be checked.

### Description
Verify that all employee salaries fall within their designated salary bands based on role, experience, and location.

### Data Files
- `data/task3_salary_analysis/employees.xlsx`: Contains employee details including current salaries
- `data/task3_salary_analysis/salary_bands.xlsx`: Contains salary ranges for each role/location/experience combination

### Task Requirements
1. For each employee, identify their applicable salary band
2. Check if current salary falls within the band range
3. Identify employees with salaries outside their bands
4. Calculate the deviation from band limits

### Solution Format
Create `solutions/task3_solution.xlsx` with:
- Column 'Flagged_Employees': Employee IDs with non-compliant salaries

### Data

[task3_salary_analysis.zip](https://github.com/user-attachments/files/17652774/task3_salary_analysis.zip)

**Comment by yufansong** [comment]
Not plan in v1.0.0.
