### ISSUE TITLE
Research task: finish up and publicize research project

### ISSUE THREAD

**Issue by zorazrw** [TheAgentCompany/TheAgentCompany#625]
## Task
Our research team recently wrote a paper about adaptive agents called "Agent Workflow Memory" (AWM) (https://ogma.lti.cs.cmu.edu/apps/files/files/7095?dir=/Documents/Research&openfile=true), we plan to publicize the paper in tomorrow morning, however, we still lack some essential materials.

Step 1. We want an intriguing teaser figure (figure 1) to demonstrate the adaptive learning process of AWM agent, i.e., its overall capabilities improve as processing more examples, by learning more and more complex skills over time, compared to the baseline agent with non-improving capabilities. To ensure clarity in the paper, save the figure in PDF format as '/workspace/teaser.pdf'. For the ease of paper layout process, do not contain excessive whitespaces around the figure content.

Step 2. We want to host a main website to publicize the paper, which we decide can be a gitlab readme page for now. Create a repository called 'agent-workflow-memory', put the paper title and abstract in it.

Step 3. Create a twitter thread to publicize the project and save it to '/workspace/thread.txt', limit each post to 140 characters. Split each post by triple empty lines. 

Finally, send the path of the teaser figure, the gitlab readme page, and twitter thread file to Wang Fang (on http://the-agent-company.com:3000/) to check if these materials are ready to publish.

## Checkpoints
- If the agent has visited the paper pdf on next cloud (1 point)
- If the agent correctly creates a teaser figure (5 points)
  - If the file path '/workspace/teaser.pdf' exists and in PDF format (1 point)
  - If the figure shows the agent capability improving over the course of processing more examples (1 point)
  - If the figure shows the agent learns more complex skills over time (1 point)
  - If the figure shows the baseline method do not improve over time (1 point)
  - If the figure do not have excessive whitespaces on the surroundings (1 point)
- If the agent correctly creates a gitlab readme page (3 points)
  - If the repository 'agent-workflow-memory' exists (1 point)
  - If a README page 'agent-workflow-memory/README.md' exists (1 point)
  - If the readme page contains the paper title and abstract (1 point)
- If the agent correctly creates a twitter thread (3 point)
  - If the file '/workspace/thread.txt' exists (1 point)
  - If each post have no more than 140 characters (1 point)
  - If the twitter thread content is about the AWM paper (1 point)
- If the agent sends over all information to Want Fang (1 point)

**Comment by yufansong** [comment]
Not plan in v1.0.0.
