### ISSUE TITLE
Research task: create paper checklist from survey paper

### ISSUE THREAD

**Issue by zorazrw** [TheAgentCompany/TheAgentCompany#626]
## Task
Our research team recently wrote a survey paper about tool-augmented language models (https://ogma.lti.cs.cmu.edu/apps/files/files/7116?dir=/Documents/Research&openfile=true). To make the project more influential, we want to maintain a gitlab page keeping track of all relevant papers.

First of all, our researchers still haven't write the abstract of the paper. Read the rest of the paper content and write an abstract, send it to Wang Fang on http://the-agent-company.com:3000/ as a draft for the abstract.

Your next task is to create a 'awesome-tool-lms' repository and create a readme file. In the readme, put different sections in the paper (besides the last "final remarks" sections) as the section names in the readme page, then list the papers mentioned in that paper section in the corresponding section in the gitlab page. Format the paper in "- {paper title}: {year}".

Then, at the bottom of readme, create another "Statistics" section, to keep track of the paper numbers we include in the paper. Draw a bar chart with section names as columns on the x-axis, and paper numbers as the y-axis. Place the image under 'assets/paper_count.jpg' and place the link in the readme.

Lastly, we also want to publicize the survey on twitter. Create a draft twitter thread in '/workspace/thread.txt' and split posts by double empty lines. Give a summary of what the project is about, and don't forget to mention the link of our paper and our gitlab readme page. 

## Checkpoints

- If the agent visits the paper link on nextcloud (1 point)
- If the agent sends Wang Fang a reasonable abstract of the paper (2 point)
- If the create a readme file (11 point)
  - If agent create the repository 'awesome-tool-lms' with README.md (1 point)
  - If agent puts 7 paper sections as separate sections in readme (1 point)
  - If paper in each section is correct (7 point)
  - If "Statistics" section and corresponding figure "assets/paper_count.jpg" exists (1 point)
  - If the paper count statistics align with the paper listed in previous sections (1 point)
- If agent creates twitter thread draft (3 point)
  - If the twitter draft file exists (1 point)
  - If the twitter summarizes the survey paper (1 point)
  - If the links of paper and gitlab readme are mentioned in tweet (1 point)

**Comment by yufansong** [comment]
Not plan in v1.0.0.
