### ISSUE TITLE
[Infra] Plane crash during reset

### ISSUE THREAD

**Issue by li-boxuan** [TheAgentCompany/TheAgentCompany#665]
https://github.com/neulab/TheAgentCompany/blob/ebe38b6393f1ffd8a307fd91f95c0cafb852f1fc/servers/api-server/server.py#L69-L72 sometimes leads to plane crash due to unknown reasons.

If possible, we should try to fix the plane crash issue.

**Comment by yufansong** [comment]
In most of the time when crash, the backend cannont launch when database are not setup quickly. It seems we have no methods to optimize. Restart can solve it.
