### ISSUE TITLE
SDE Task: Create and run web crawler in go using Colly

### ISSUE THREAD

**Issue by yang-mingyang** [TheAgentCompany/TheAgentCompany#670]
Our AI researcher is reaching out for help! She's investigating into how to fast crawl data from web pages. She ran into a powerful tool Colly (http://the-agent-company.com:8929/root/colly) and would like to learn how to use it. Unfortunately, though she's quite an expert in Python, she never used GoLang before. She needs someone to set up the go environment for her and write an example go file to crawl the data that can be easily run.

## Task.md
Install go and add go binary to system path. Refer to http://the-agent-company.com:8929/root/colly and use Colly to write a web crawler program in go that crawls data from http://the-agent-company.com:8929/root/colly. The crawler should store all visited links to /workspace/visited_links.txt. In case the program runs forever, your program should stop after visiting 10 links. Save your program in /workspace/web_crawler.go. Make sure you downloaded all required module so others can easily execute `go run /workspace/web_crawler.go` in command line to run the program.

## Checkpoints
- Run `go version` and it return a go version successfully. (2pt)
- Run `go run /workspace/web_crawler.go` and the program exits successfully. (2pt)
- /workspace/visited_links.txt exists (1pt)
- /workspace/visited_links.txt contains 10 links. (1pt)

**Comment by yufansong** [comment]
Not plan in v1.0.0.
