### ISSUE TITLE
SDE task: make a website for our company

### ISSUE THREAD

**Issue by zorazrw** [TheAgentCompany/TheAgentCompany#779]
## Task

We are about to pulicize our company and it would be very helpful to create a website to present all our members. According to the information in the personnel file at https://ogma.lti.cs.cmu.edu/apps/files/files/1104?dir=/Documents/Human%20Resources%20Team&openfile=true, list the name, job title, and photo for each person. 
To obtain everyone's photos, try search for it in all files folder (https://ogma.lti.cs.cmu.edu/apps/files/files?dir=/). If you cannot find it, ask that person in the channel and see if they can send their photo to you. If you cannot get responses within a minute, use a placeholder for their photos on the website for now.
Lastly, share the path of the source html file (saved under '/workspace/') of the website that you built in the #general channel on http://the-agent-company.com:3000/. Because some non-engineer members may not know how to open a HTML file, also create a screenshot of the rendered website under '/workspace/', and send the image path to the #general channel as well.

## Note
Could ask several NPCs to provide photos, and some others do not.

## Checkpoints
- Check if the HTML file contains the name and job title for everyone in the personnel file
- Check if the agent asks everyone for their photos
- Check if the HTML file contains photos for the several NPCs provided their photos
- Check if the agent uses placeholder images for other people
- Check if the agent sends both paths of the HTML file and its rendered screenshot in #general channel

**Comment by yufansong** [comment]
Not plan in v1.0.0.
